name: PR 3986 license preflight

on:
  push:
    branches:
      - tmp-regenerate-preview-bundle

permissions:
  contents: read

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Check Package Licenses
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        with:
          base-ref: 102966bf8affb3e57bc93c02f198b772079562f8
          head-ref: 2c1f0cdf1f6a5b25b3e363d6e08f85b8ec21099f
          config-file: angular/dev-infra/github-actions/linting/licenses/dependency-review-config.yml@main
          allow-dependencies-licenses: 'pkg:npm/renovate, pkg:npm/@renovatebot/detect-tools'
          show-openssf-scorecard: false
